Repository utd-multimedia/add-far, pull requests merged in 2019-04, with the labels that each got.

#1 Add documentation to files. Change file paths to be OS agnostic. Move…
  config.json
  findAttackDir.m
  getCorrespondance2Dto3D.m
  getOBB.m
  loadRGBDetectionResults.m
  pointsInBB.m
  readCalibration.m
  readLabels.m
  visualizeForgedData.m
  writeLabels.m
  writePC2Bin.m
  writeRGBDetctResult.m
Labels: enhancement

#2 Add documentation to files. Change file paths to be OS agnostic. Move…
  boxCenterCam2Velo.m
  checkValidBB.m
  computeBox3D.m
  config.json
  cornersCam2Velo.m
  cornersVelo2LeftI.m
  createAttacks.m
  createAttacks_8_17.m
  createAttacks_8_21.m
  displayAttacks.m
  drawBox3D.m
  subtractiveAttackExplanationImage.png
Labels: enhancement

#3 Remove hardcoded paths.
  config.json
  createAttacks.m
  createAttacks_8_17.m
  createAttacks_8_21.m
Labels: bug

#4 Update readCalibration.m
  readCalibration.m
Labels: enhancement

#5 Update createAttacks_8_21.m
  createAttacks_8_21.m
Labels: bug

#6 Update README.md
  README.md
Labels: enhancement

#7 Update documentation
  deleteAllDatasetFiles.m
  getCollision.m
Labels: bug, enhancement

#8 Update documentation.
  getCollision.m
Labels: enhancement
